name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.21.x
    - name: Lint
      run: make lint

  test:
    strategy:
      matrix:
        platform: 
        - ubuntu-latest
        go:
        - 1.19.x
        - 1.20.x
        - 1.21.x
        - 1.22.x
        goarch:
        - amd64
        include:
        - platform: ubuntu-latest
          go: 1.21.x
          goarch: '386'  # Verify fieldalignment on 32 bit platforms.
        - platform: macos-latest
          go: 1.21.x
          goarch: amd64
        - platform: windows-latest
          go: 1.21.x
          goarch: amd64
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: make test
      env:
        GOARCH: ${{ matrix.goarch }}
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERAGE_VERSION: '1.21'
